name: 'Environment Setup'
description: 'GitHub action which sets up the runner environment'
inputs:
  secretNames:
    description: 'List of secret names'
    required: true
  awsRegion:
    description: 'The AWS region to use'
    required: true
    default: us-east-1
runs:
  using: 'node12'
  main: 'dist/index.js'
