name: 'Environment Setup'
description: 'GitHub action which sets up the runner environment'
inputs:
  environmentName:
    description: 'Environment name'
    required: true
  regionName:
    description: 'Region name'
    required: true
  secretNames:
    description: 'List of secret names'
    required: false
  variableNames:
    description: 'List of variable names'
    required: false
  npmTokenName:
    description: 'The NPM token name'
    required: true
    default: GITHUB_NPM_TOKEN
runs:
  using: 'node12'
  main: 'bin/index.js'
